BOT_NAME = 'b1'

SPIDER_MODULES = ['b1.spiders']
NEWSPIDER_MODULE = 'b1.spiders'

USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
CONCURRENT_REQUESTS = 16
COOKIES_ENABLED = False
DEPTH_LIMIT = 0

AUTOTHROTTLE_ENABLED = False

CLOSESPIDER_PAGECOUNT = 0
CLOSESPIDER_ITEMCOUNT = 0
